repository:
  name: the-copy

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - build-backend
          - build-frontend
          - audit
          - secret-scan
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
      restrictions: null
      required_linear_history: true
